const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {Economy,STATS,SKILLS,TALENT_RINGS,TALENT_NODES,TALENT_BY_ID,RING_GATE,MUTATIONS,MUTATION_BY_ID,RARITY,RARITY_BY_KEY,FACE_WEIGHTS,EPOCHS,epochIndexFor,globalScaleFor,STAGES,stageIndexFor,hashSeed,mulberry32,mutateFor,rarityTableFor,Ke,Kb,xpPerEnemy,xpPerBuilding,xpPerDistrict,sanitize}=require('../progression.js');
const Rig=require('../rig.js');
let e=new Economy();assert.equal(e.speed(),38,'heavier initial walking speed');e.data.levels.stride=4;assert.equal(e.speed(),46,'stride upgrades still improve speed');e.data.levels.stride=1;assert(e.upgrade('power'));assert.equal(e.data.levels.power,2);e.data.energy=0;let before=e.data.energy;assert(!e.upgrade('atomic'));assert.equal(e.data.energy,before);e.data.dna=9;assert(!e.unlock('meltdown'),'prerequisite enforced');assert(e.unlock('pierce'));assert(e.unlock('chain'));assert(e.unlock('meltdown'));assert(!e.unlock('meltdown'));e.data.energy=10000;e.data.policy='atomic';assert.equal(e.data.auto,false);e.autoSpend();assert.equal(e.data.energy,10000,'default preserves nuclear reserves');e.data.auto=true;e.autoSpend();assert(e.data.levels.atomic>1);
let off=new Economy();off.data.lastSeen=Date.now()-12*3600*1000;let report=off.offline(Date.now());assert.equal(report.seconds,28800);assert(report.capped);assert.equal(off.offline(Date.now()),null,'offline credit cannot duplicate');let saved=new Economy(JSON.parse(off.serialize(Date.now(),{x:900})));assert.equal(saved.data.energy,off.data.energy);assert.equal(saved.data.world.x,900);let bad=new Economy({version:3,energy:-5,levels:{power:-2},level:'oops',dna:NaN,skills:['hack']});assert.equal(bad.data.energy,0);assert.equal(bad.data.levels.power,1);assert.deepEqual(bad.data.skills,[]);console.log('PASS economy: upgrade pricing, prerequisites, policies, save, offline cap and sanitization');
let pose1=Rig.pose({x:400,ground:590,moving:true,step:0,action:{name:'walk',t:0}},0),pose2=Rig.pose({x:400,ground:590,moving:true,step:1.5,action:{name:'walk',t:0}},1);assert.notEqual(pose1.bones.shin.a,pose2.bones.shin.a);assert.notEqual(pose1.bones.tail_tip.a,pose2.bones.tail_tip.a);for(let name of ['claw','beam','stomp','roar','tail']){let pose=Rig.pose({x:400,ground:590,step:0,angle:.3,action:{name,t:.7}},1);assert(Object.values(pose.bones).every(b=>Number.isFinite(b.x)&&Number.isFinite(b.y)&&Number.isFinite(b.a)));}console.log('PASS rig: independent limb motion, parent transforms and all animation states');
let nodes=new Map(),listeners={},storage=new Map();let grad={addColorStop(){}};let ctx=new Proxy({createLinearGradient:()=>grad},{get:(t,k)=>k in t?t[k]:(()=>{}),set:(t,k,v)=>(t[k]=v,true)});function node(id){if(!nodes.has(id)){let el={style:{setProperty(){}},dataset:{},classList:{toggle(){},add(){},remove(){}},setAttribute(){},getContext:()=>ctx,hidden:false,textContent:'',innerHTML:'',disabled:false,querySelector:()=>({textContent:'',style:{setProperty(){}}}),querySelectorAll:()=>[]};nodes.set(id,el);}return nodes.get(id);}
class ImageMock{set src(v){this.complete=true;this.naturalWidth=300;this.naturalHeight=300;queueMicrotask(()=>this.onload?.());}}
let randomSeed=76123;const testMath=Object.create(Math);testMath.random=()=>{randomSeed=(Math.imul(randomSeed,1664525)+1013904223)>>>0;return randomSeed/4294967296;};
const window={IdleProgression:{Economy,STATS,SKILLS,TALENT_RINGS,TALENT_NODES,TALENT_BY_ID,RING_GATE,MUTATIONS,MUTATION_BY_ID,RARITY,RARITY_BY_KEY,FACE_WEIGHTS,EPOCHS,epochIndexFor,globalScaleFor,STAGES,stageIndexFor,hashSeed,mulberry32,mutateFor,rarityTableFor,Ke,Kb,xpPerEnemy,xpPerBuilding,xpPerDistrict,sanitize},KaijuRig:Rig,addEventListener:(k,f)=>listeners[k]=f};let sandbox={window,KaijuRig:{...Rig,Skeleton:class{constructor(){this.ready=true;}draw(){}}},console,Math:testMath,Set,Array,Map,Date,String,Number,Image:ImageMock,document:{getElementById:node,createElement:()=>node(Math.random()),hidden:false,addEventListener:(k,f)=>listeners[k]=f,body:{classList:{toggle(){}}}},localStorage:{getItem:k=>storage.get(k),setItem:(k,v)=>storage.set(k,v)},performance:{now:()=>0},requestAnimationFrame(){},setTimeout(fn){fn();return 0;}};
let src=fs.readFileSync(require('node:path').join(__dirname,'../game.js'),'utf8').replace(/\}\)\(\);\s*$/,`window.test={update,render,save,generateWorld,defeat,crash,begin,damageBuilding,worldSnapshot,get state(){return {data,p,buildings,enemies,crashCount,particles,fires,beam,rigState,news,economy};}};})();`);vm.runInNewContext(src,sandbox);let api=window.test;api.state.data.auto=true;
let main=api.state.buildings.find(b=>b.layer===1);assert(main.max>=780);api.damageBuilding(main,api.state.economy.power(),'claw');api.damageBuilding(main,api.state.economy.power(),'claw');assert(!main.dead&&main.hp>main.max*.7,'main building survives repeated initial claws');
let currentSave=api.worldSnapshot(),ratio=main.hp/main.max,id=main.id;api.generateWorld(currentSave);assert(Math.abs(api.state.buildings.find(b=>b.id===id).hp/api.state.buildings.find(b=>b.id===id).max-ratio)<1e-9,'new save preserves damage ratio');
api.generateWorld({district:1,x:420,buildings:[{id,hp:115,dead:false},{id:'1-1',hp:0,dead:true}]});main=api.state.buildings.find(b=>b.id===id);assert.equal(main.hp/main.max,.5,'legacy save retains half damaged condition');assert(api.state.buildings.find(b=>b.id==='1-1').dead,'legacy ruins stay destroyed');api.generateWorld();
console.log('PASS tougher buildings: multiple hits, current save and legacy damage migration');
let seen=new Set(),crashSeen=false,counts={},previousAction=null;for(let i=0;i<(process.argv.includes('--long')?1800:600)*60;i++){api.update(1/60);seen.add(api.state.p.action.name);if(api.state.p.action!==previousAction){previousAction=api.state.p.action;counts[previousAction.name]=(counts[previousAction.name]||0)+1;}if(api.state.crashCount>0)crashSeen=true;if(i%1200===0)api.render();if(api.state.data.district>=(process.argv.includes('--long')?6:3))break;}
let s=api.state;console.log('IDLE RUN',JSON.stringify({district:s.data.district,level:s.data.level,buildings:s.data.cleared,kills:s.data.kills,crashes:s.crashCount,stats:s.data.levels,skills:s.data.skills,actions:[...seen],counts}));assert(s.data.district>=2,'autonomous progression clears first district');assert(s.data.level>=3,'idle evolution accumulates XP');assert(s.data.cleared>40);assert(s.data.skills.length>=1);assert(crashSeen,'airborne destruction reaches ground explosion');for(let name of ['walk','claw','beam','stomp','roar','tail'])assert(seen.has(name),'AI selects '+name);assert(s.p.x>400);assert(s.p.hp===undefined,'player has no health/death mechanic');api.save();let payload=JSON.parse(storage.get('gnn-kaiju-idle-v3'));assert.equal(payload.world.district,s.data.district);assert(s.particles.length<=700);assert(s.fires.length<=60);console.log('PASS autonomous world: districts, skills, all attacks, airborne crashes, persistence, bounded particles');
assert((counts.claw||0)+(counts.stomp||0)+(counts.tail||0)>(counts.beam||0)*3,'melee dominates automatic combat');console.log('PASS combat pacing: melee actions exceed laser casts by more than 3 to 1');
let a=s.enemies.find(x=>x.state==='alive');if(a){api.defeat(a,'claw');assert.equal(a.state,'flying');let oldKills=s.data.kills;api.defeat(a,'claw');assert.equal(s.data.kills,oldKills,'no duplicate kill reward');api.crash(a);assert.equal(a.state,'exploding');}console.log('PASS destruction: launch, crash transition and single reward');
api.state.data.skills=[];api.begin('beam',api.state.enemies[0]);assert.equal(api.state.p.cooldowns.beam,28,'base beam cooldown 28 s');api.state.data.skills=['overdrive'];api.begin('beam',api.state.enemies[0]);assert.equal(api.state.p.cooldowns.beam,21,'evolved beam cooldown 21 s');api.generateWorld();api.state.p.x=500;api.state.p.cooldowns={beam:0,stomp:0,tail:0,roar:0};api.update(1/60);assert.equal(api.state.p.action.name,'stomp','nearby destruction takes priority over ready laser');console.log('PASS laser cooldown and melee priority');
api.state.data.skills=SKILLS.map(s=>s.id);api.generateWorld();let red=0;for(let i=0;i<3;i++){api.begin('beam',api.state.enemies[2]);if(api.state.p.action.super)red++;for(let j=0;j<250;j++)api.update(1/60);}assert.equal(red,1,'meltdown fires every third cast');let boosted=new Economy({version:3,skills:['harvest','momentum','overdrive'],lastSeen:Date.now()-60000});assert.equal(boosted.offline(Date.now()).efficiency,.9);console.log('PASS final skill effects: third-cast red beam and 90% offline efficiency');
